#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer 
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.9
apt-get -y update
apt-get -y install haproxy=2.9.\*
echo -e "\nfrontend bit-tech-backend\n\tbind *:80\n\tmode http\n\tdefault_backend bit-tech-backend\n\nbackend bit-tech-backend\n\tbalance roundrobin\n\tserver 470751-web-01 54.144.198.193 check port 80\n\tserver 470751-web-02 100.24.237.90 check port 80" | sudo tee /etc/haproxy/haproxy.cfg
service haproxy restart
