#!/usr/bin/env bash
#Creating script that use nested loop
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minutes=1
    while [ $minutes -lt 60 ]
    do
	echo "$minutes"
	((minutes++))
    done
    ((hour++))
done
